services:
  postgres:
    image: postgres:13
    environment:
     - POSTGRES_DB=adso_db
     - POSTGRES_USER=root
     - POSTGRES_PASSWORD=123456
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    #   - ./certs:/certs
    #   - ./postgresql.conf:/etc/postgresql/postgresql.conf
    #   - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
    # command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports: 
      - "5050:80"

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=mi_sql_db
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=123456
    ports: 
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
     - MYSQL_ROOT_PASSWORD=123456
     - PMA_HOST=mysql
    ports:
      - '8080:80'


